########################################################################################

# This Makefile generated by GoMakeGen 0.5.0 using next command:
# gomakegen .

########################################################################################

.PHONY = fmt all clean deps deps-test test

########################################################################################

all: vgrepo

vgrepo:
	go build vgrepo.go

deps:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/essentialkaos/ek.v9
	go get -d -v pkg.re/essentialkaos/go-linenoise.v3

deps-test:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/check.v1

test:
	go test -covermode=count ./...

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

clean:
	rm -f vgrepo

########################################################################################
